name: gh-pages
on:
  push:
    branches:
      - dev
    paths:
      - 'docs/*'
      - '.github/workflows/gh-pages.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install dependencies
        run: pip3 install -r docs/requirements.txt
      - name: build
        run: make docs
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build
          cname: rearq.long2ice.cn
